spring.datasource.url=jdbc:postgresql://admin:2JuXEsHJpgfFJwbdu2lHKO6rpRviT87t@dpg-d6rj3sia214c73d1r1qg-a.oregon-postgres.render.com/veterinaria_1vox
spring.datasource.username=admin
spring.datasource.password=2JuXEsHJpgfFJwbdu2lHKO6rpRviT87t
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update