spring.application.name=mascotas

# URL Directa con el prefijo jdbc: indispensable para Java
spring.datasource.url=jdbc:postgresql://admin:2JuXEsHJpgfFJwbdu2lHKO6rpRviT87t@dpg-d6rj3sia214c73d1r1qg-a.oregon-postgres.render.com/veterinaria_1vox
spring.datasource.username=admin
spring.datasource.password=2JuXEsHJpgfFJwbdu2lHKO6rpRviT87t
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto para Render
server.port=${PORT:8080}
logging.level.org.hibernate.SQL=DEBUG
