spring.application.name=mascotas
spring.datasource.url=jdbc:postgresql://localhost:5432/mascotas-data-base
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

#mostrar las consultas SQL
spring.jpa.show-sql=true


#configuración para que actualice el esquema
spring.jpa.hibernate.ddl-auto=update

#aptimiza la base de datos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

