spring.application.name=mascotas

# URL de la base de datos
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/mascotas-data-base}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

# Mostrar consultas SQL
spring.jpa.show-sql=true

# Configuracion del esquema
spring.jpa.hibernate.ddl-auto=update

# Dialecto para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto para Render
server.port=${PORT:8080}